service: infrastructure
frameworkVersion: '3'

# these two lines are required for serverless offline to reference a local .env file
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  # the order of these plugins is important
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iam:
    role: LambdaRole
  environment:
    BRANCH_NAME: ${opt:stage}
    DB_PASSWORD: ${env:POSTGRES_PW}
    # DB_HOST: ${self:custom.pgHost.${opt:stage}}

custom:
  serverless-offline:
    httpPort: 4000
    ignoreJWTSignature: true

functions:
  get-generic:
    handler: handlers/generic-handler.getAll
    events:
      - httpApi:
          path: /transactions
          method: get

resources:
  Conditions:
    IsProd:
      Fn::Equals:
        - ${opt:stage}
        - prod
  Resources:
    LambdaRole: ${file(./resources/LambdaRole.yml)}
    RDSPostgres: ${file(./resources/RDSPostgres.yml)}
    # Route53HostedZone: ${file(./resources/Route53HostedZone.yml)}
