name: 'infrastructure-deployment'

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - '**/infrastructure/**'
      - '**/.github/workflows/infrastructure-deployment.yml'
  workflow_dispatch:

permissions:
  id-token: write # required for aws-actions/configure-aws-credentials
  contents: read # required to checkout the code from the repo

jobs:
  deploy:
    name: 'deploy'
    env:
      AWS_REGION: 'us-east-2'
      POSTGRES_PW: ${{secrets.POSTGRES_PW}}
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.5

      # extract branch name on pull request
      - name: Set environment
        run: BRANCH=${{ steps.branch-name.outputs.current_branch }}

      - name: Configure AWS credentials from Dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::xxxxx:role/github-role # replace with your role arn
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install
        working-directory: infrastructure
      - name: Deploy serverless
        run:
          node ./node_modules/serverless/bin/serverless.js deploy --stage ${{
          steps.branch-name.outputs.current_branch }}
        env:
          SLS_DEBUG: 1
